"""activity

Revision ID: 2a9adaed4bd9
Revises: e21f618f0616
Create Date: 2024-05-26 11:10:13.036716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a9adaed4bd9'
down_revision: Union[str, None] = 'e21f618f0616'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_url', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('video_url', sa.String(), nullable=True),
    sa.Column('img_url', sa.String(), nullable=True),
    sa.Column('post_content', sa.String(), nullable=False),
    sa.Column('like_count', sa.Integer(), nullable=False),
    sa.Column('comment_count', sa.Integer(), nullable=False),
    sa.Column('repost_count', sa.Integer(), nullable=False),
    sa.Column('post_date', sa.String(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('profile_url', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('post_timestamp', sa.DateTime(), nullable=False),
    sa.Column('agent_id', sa.String(), nullable=False),
    sa.Column('container_id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('activities')
    # ### end Alembic commands ###
